### ISSUE TITLE
[Bug]: Merge Pets non-functional in Patch 10.2

### ISSUE THREAD

**Issue by wordup834** [bkader/Skada-Damage-Meter#10]
### Are you using the latest version of the addon?

- [X] Yes
- [ ] No

### Addon Version

Version 1.8.85 - Date: 2023-11-09 @ 07:30 GMT

### Did you try having only this addon enabled?

- [ ] Yes
- [X] No

### Current Behavior

When pets are summoned, the owner/player is no longer the primary damage source instead of being merged together. They are instead bumped to number 2, and the pet that triggers the error also does not appear on the main window either.

### Expected Behavior

Pets to be merged as one combined result.

### Lua Error

N/A

### Reproduction Steps

Have merge pets enabled
Enter Combat
Summon any temporary guardian

### Last Good Version

10/30/2023

### Screenshots

![skada](https://github.com/bkader/Skada-Damage-Meter/assets/36289173/c88de15d-475e-41e5-b3fe-25ce23dd7646)

**Comment by Deimrus** [comment]
Confirm. Merge pets option works incorrectly.

**Comment by bkader** [comment]
Hello @wordup834 . Thanks for reporting this. It should be `Version: 1.8.85 - Date: 2023-08-10 @ 12:39`
Please [try this version](https://bit.ly/SkadaMG) (_`Version: 1.8.86 - Date: 2023-11-07 @ 07:57`_) and see if it's fixed because there was a small problem with flags that I fixed and it might have fixed the issue (_get `3.4.x`, it's for both classic and retail_).

**Comment by wordup834** [comment]
> Hello @wordup834 . Thanks for reporting this. It should be `Version: 1.8.85 - Date: 2023-08-10 @ 12:39` Please [try this version](https://bit.ly/SkadaMG) (_`Version: 1.8.86 - Date: 2023-11-07 @ 07:57`_) and see if it's fixed because there was a small problem with flags that I fixed and it might have fixed the issue (_get `3.4.x`, it's for both classic and retail_).

Unfortunately not, issue still present using 3.4.x - issue possibly related to requiring server name in owner name now following cross faction guilds?

**Comment by bkader** [comment]
I took a look at the changes and noticed that the game is always adding the realm's name even if players are from the same realm. If you [test out this file](https://github.com/bkader/Skada-Damage-Meter/files/13313664/Init.zip) it would be great! Simply drop it inside `Skada\Core` folder making sure it asks you to replace the file `Init.lua`.

**Comment by wordup834** [comment]
This fixes the issue yes, looks like it's merging pets again, Thanks for the fix!

**Comment by ArenfeIdt** [comment]
Seems to be broken once again for me - i have tried both the v1.8.85 + init file and the v1.8 .86 + init file.

**Comment by bkader** [comment]
Thanks for reporting this @ArenfeIdt .. I could test the addon after ages of updates and I could confirm it. Try to update the addon from the [mega folder](https://bit.ly/SkadaMG), I believe I fixed it.

**Comment by ArenfeIdt** [comment]
Yes, it works again now - however, the Version in the Mega Folder on its own does not work for me. Only after adding the Init.lua File you posted earlier in this Issue Report does it work. Just tested it with the Priest Shadowfiend, BM Hunter Pets and the Voidwalker Warlock Pet. All of them merge properly now. Probably better if you add the Init.lua File directly to the new Version ZIP.

**Comment by bkader** [comment]
There isn't a big difference between both files. However, the file I posted had an issue, it was using the player's realm name (_yours_) even for players from other realms, so I just edited that part to use the realm name of each player.

**Comment by ArenfeIdt** [comment]
Maybe something is different because i use the Setting to not display Realm Names.

**Comment by bkader** [comment]
It shouldn't affect anything, that option simply strips off the realm name, for display purposes, not data.

**Comment by ArenfeIdt** [comment]
Hmm, i just know that if i use the Init file that comes with the entire Skada Folder it doenst work for me - only after using the extra init file you posted does it work for me,
